hdpack 2.0.3

diff --git a/hdpack b/hdpack
--- a/hdpack
+++ b/hdpack
@@ -13,7 +13,7 @@ ___cvs(){ [ -z "$1" ] && { echo 0;return;};[ -z "$2" ] && { echo 1;return;};loca
 [ -n "$(echo "$@" | sed -nr 's!(--dry)!\1!p')" ] || [ -n "$(echo "$@" | sed -nr 's!(--verbose)!\1!p')" ] && { export __log_trace__=1;export DBG_RUN=1;export TMP_DEBUG="true";export __sr_TMP_DEBUG=1;export __sr_RUN_DIE_TRACE=1;__sr_NO_RUN_DIE_TRACE=0;} # ___srD=1; # verbose: 1.1.11, dry implies verbose
 
 
-VERSION="2.0.2"
+VERSION="2.0.3"
 SHORT_DESCRIPTION="(${VERSION})hdpack: pack quickly a .tar.gz(.xz) archive"
 
 # this is hdpack: pack stuff quickly
@@ -154,7 +154,9 @@ https://raw.githubusercontent.com/dhilfer/hdtools/main/hdpack
 if true; then                                                           # options
 # options
 CMD_LINE_OPT__DIRECTORY="."  # change to directory
+CMD_LINE_OPT__OUT=""
 CMD_LINE_OPT__SEPARATE=0  #
+CMD_LINE_OPT__TAR_OPTIONS=""
 CMD_LINE_OPT__XZ=0
 CMD_LINE_OPT__VERSION=0
 CMD_LINE_OPT__VERBOSE=0
@@ -175,11 +177,18 @@ common use cases. You can create a .tar.xz by choosing option: --xz/-x.
 
   -C  --directory DIR_PATH  change to directory before pack
 
+  -o  --out PATH            if packing ONE archive, don't try to guess
+                            name of output file, use PATH instead.
+                            If packing --separate/-S archives, place
+                            auto (name-)guessed result files in PATH dir
+
   -S  --separate            make separate archives, instead of pack
                             everything into big one
 
   -x  --xz                  pack a .tar.xz instead of .tar.gz
 
+  -O  --tar-options         additional options to pass to tar
+                            Example: --tar-options \"--preserve permissions --ignore-failed-read\"
 
 ------------ OTHER OPTIONS ---------------------------------------------
 
@@ -219,6 +228,10 @@ parse_all_options()
                 CMD_LINE_OPT__DIRECTORY="${2}"
                 shift 2 ; shifted=$((shifted+2)) ;;
 
+            --out|-o)
+                CMD_LINE_OPT__OUT="${2}"
+                shift 2 ; shifted=$((shifted+2)) ;;
+
             # make ONE archive, instead of separate ones
             --separate|-S)
                 CMD_LINE_OPT__SEPARATE=1
@@ -227,6 +240,11 @@ parse_all_options()
             --xz|-x)
                 CMD_LINE_OPT__XZ=1
                 shift 1 ; shifted=$((shifted+1));;
+
+            --tar-options|-O)
+                CMD_LINE_OPT__TAR_OPTIONS="${2}"
+                shift 2 ; shifted=$((shifted+2)) ;;
+
 
             --version|-V)
                 CMD_LINE_OPT__VERSION=1
@@ -300,15 +318,16 @@ escape_paths() #(*esc_p, ...)
     eval "export ${export_var_esc_p}='${ret_esc_p}'"
     return 0
 }
-pack_ONE_tar() #(result_file_path, ch_dir, do_xz, ...)
+pack_ONE_tar() #(result_file_path, ch_dir, do_xz, add_tar_opts, ...)
 {
-    local __fn="pack_ONE_tar"; _chkargsm "${__fn}" 4 "$@"
+    local __fn="pack_ONE_tar"; _chkargsm "${__fn}" 5 "$@"
 
     local result_file_path=; result_file_path="${1}";
     local ch_dir=; ch_dir="${2}";
     local do_xz=; do_xz="${3}";
+    local add_tar_opts=; add_tar_opts="${4}";
 
-    shift 3
+    shift 4
 
     if [ ! $# -gt 0 ]; then
         logerror "you need to specify what to pack"
@@ -347,9 +366,9 @@ pack_ONE_tar() #(result_file_path, ch_dir, do_xz, ...)
     # build tar cmd (may using this wisdom)
     # https://gist.github.com/Kautenja/af670104f13c94f92b69ce054ee96b42
     if [ -n "${PV_TOOL}" ]; then
-        cmd="${tar_cd} ${TAR_TOOL} -cf - ${ALL_PATHS} | pv -tebap -s ${size_to_pack} | ${pack_tool} > ${result_file_path}"
+        cmd="${tar_cd} ${TAR_TOOL} ${add_tar_opts} -c -f - ${ALL_PATHS} | pv -tebap -s ${size_to_pack} | ${pack_tool} > ${result_file_path}"
     else
-        cmd="${tar_cd} ${TAR_TOOL} -cf - ${ALL_PATHS} | ${pack_tool} > ${result_file_path}"
+        cmd="${tar_cd} ${TAR_TOOL} ${add_tar_opts} -c -f - ${ALL_PATHS} | ${pack_tool} > ${result_file_path}"
     fi
 
     local _mto=
@@ -359,7 +378,10 @@ pack_ONE_tar() #(result_file_path, ch_dir, do_xz, ...)
     if [ "${size_to_pack_human}" = "0" ]; then
         size_to_pack_human="<1"
     fi
-    lognotice "pack ${size_to_pack_human} [MiB]: '${1}'${_mto} to '${result_file_path}'"
+    lognotice "pack ca. ${size_to_pack_human} [MiB]: '${1}'${_mto} to '${result_file_path}'"
+    if [ -n "${add_tar_opts}" ]; then
+        lognotice "using additional tar opts: ${add_tar_opts}"
+    fi
     run "${cmd}"
     return $?
 }
@@ -600,6 +622,53 @@ Try following:
 }
 fi
 
+makeid() #(len, *id)
+{
+    local __fn="makeid"; _chkargs "${__fn}" 2 "$@"
+
+    local len=; len="${1}";
+    local export_var_id=; export_var_id="${2}";
+    eval "export ${export_var_id}=";
+    local ret_id=
+
+    # ---
+    local ran=
+    local i=0
+    while [ ${i} -lt ${len} ]; do
+        ran=$(grep -m1 -ao '[0-9a-f]' /dev/urandom | head -n1)
+        ret_id="${ret_id}${ran}"
+        i=$((i+1))
+    done
+    # ---
+
+    # return values
+    eval "export ${export_var_id}='${ret_id}'"
+    return 0
+}
+handle_target_dir() #(target_dir)
+{
+    local __fn="handle_target_dir"; _chkargs "${__fn}" 1 "$@"
+
+    local target_dir=; target_dir="${1}";
+
+    if [ ! -d "${target_dir}" ]; then
+        if [ -e "${target_dir}" ]; then
+            die "'${target_dir}' exists already and it's not a dir!"
+        fi
+        cmd="mkdir -p '${CMD_LINE_OPT__OUT}'"
+        run_d "${cmd}"
+    fi
+
+    # make sure its writable
+    makeid 16 _I_ID
+    cmd="touch '${target_dir}/${_I_ID}'  ${stderr_stdout_to_dev_null}"
+    run "${cmd}" || die "'${target_dir}': is not writable"
+    cmd="rm '${target_dir}/${_I_ID}'  ${stderr_stdout_to_dev_null}"
+    run "${cmd}" || die "'${target_dir}': is not writable"
+
+    return 0
+}
+
 main()
 {
     parse_all_options "$@"
@@ -628,15 +697,32 @@ main()
 
     if [ "${CMD_LINE_OPT__SEPARATE}" != "1" ] ; then
         # we pack ONLY ONE archive
-        guess_result_path RESULT_FILE_PATH "${1}" "${__cwd__}" "${CMD_LINE_OPT__XZ}" # take first given name
-        pack_ONE_tar "${RESULT_FILE_PATH}" "${CMD_LINE_OPT__DIRECTORY}" "${CMD_LINE_OPT__XZ}" "$@"
+        if [ -z "${CMD_LINE_OPT__OUT}" ]; then
+            guess_result_path RESULT_FILE_PATH "${1}" "${__cwd__}" "${CMD_LINE_OPT__XZ}" # take first given name
+        else
+            # CMD_LINE_OPT__OUT must NOT be a dir
+            if [ -d "${CMD_LINE_OPT__OUT}" ]; then
+                logerror "'${CMD_LINE_OPT__OUT}' is an existing dir"
+                die "if you specify --out/-o option for packing an single (non --separate/-S) archive, you must NOT specify an existing dir!"
+            fi
+            RESULT_FILE_PATH=${CMD_LINE_OPT__OUT}
+        fi
+
+        handle_target_dir "${RESULT_FILE_PATH%/*}" # or die
+
+        pack_ONE_tar "${RESULT_FILE_PATH}" "${CMD_LINE_OPT__DIRECTORY}" "${CMD_LINE_OPT__XZ}" "${CMD_LINE_OPT__TAR_OPTIONS}" "$@"
         return $?
     fi
 
     # otherwise we pack more than one archive
+    local guess_here="${__cwd__}"
+    [ -n "${CMD_LINE_OPT__OUT}" ] && guess_here="${CMD_LINE_OPT__OUT}"
+    handle_target_dir "${guess_here}" # or die
+
     while [ "$#" -gt 0 ] ; do
-        guess_result_path RESULT_FILE_PATH "${1}" "${__cwd__}" "${CMD_LINE_OPT__XZ}" # take own name
-        pack_ONE_tar "${RESULT_FILE_PATH}" "${CMD_LINE_OPT__DIRECTORY}" "${CMD_LINE_OPT__XZ}" "${1}"
+
+        guess_result_path RESULT_FILE_PATH "${1}" "${guess_here}" "${CMD_LINE_OPT__XZ}" # take own name
+        pack_ONE_tar "${RESULT_FILE_PATH}" "${CMD_LINE_OPT__DIRECTORY}" "${CMD_LINE_OPT__XZ}" "${CMD_LINE_OPT__TAR_OPTIONS}" "${1}"
         shift 1
     done
 
